export const data = [
	{
		id: 1,
		orderId: '#455fdf54545',
		price: '$656',
		paymentStatus: 'pending',
		orderStatus: 'pending',
		active: 'View',
	},
	{
		id: 2,
		orderId: '#455fdf54545',
		price: '$656',
		paymentStatus: 'pending',
		orderStatus: 'pending',
		active: 'View',
	},
	{
		id: 3,
		orderId: '#455fdf54545',
		price: '$656',
		paymentStatus: 'pending',
		orderStatus: 'pending',
		active: 'View',
	},
	{
		id: 4,
		orderId: '#455fdf54545',
		price: '$656',
		paymentStatus: 'pending',
		orderStatus: 'pending',
		active: 'View',
	},
	{
		id: 5,
		orderId: '#455fdf54545',
		price: '$656',
		paymentStatus: 'pending',
		orderStatus: 'pending',
		active: 'View',
	},
	{
		id: 6,
		orderId: '#455fdf54545',
		price: '$656',
		paymentStatus: 'pending',
		orderStatus: 'pending',
		active: 'View',
	},
	{
		id: 7,
		orderId: '#455fdf54545',
		price: '$656',
		paymentStatus: 'pending',
		orderStatus: 'pending',
		active: 'View',
	},
	{
		id: 8,
		orderId: '#455fdf54545',
		price: '$656',
		paymentStatus: 'pending',
		orderStatus: 'pending',
		active: 'View',
	},
	{
		id: 9,
		orderId: '#455fdf54545',
		price: '$656',
		paymentStatus: 'pending',
		orderStatus: 'pending',
		active: 'View',
	},
	{
		id: 10,
		orderId: '#455fdf54545',
		price: '$656',
		paymentStatus: 'pending',
		orderStatus: 'pending',
		active: 'View',
	},
];
